--Find the total number customers by countries
select
count(customer_key) customers_by_country,
country
from gold.dim_customers
group by country;
--find total customers by gender
select
count(customer_key) customers_by_gender,
gender
from gold.dim_customers
group by gender;
--find total products by category
select
count(product_key) as product_by_category,
category
from gold.dim_products
group by category;
--Whats is the average costs in each category?
select
round(avg(cost),2) as avg_cost,
category
from gold.dim_products
group by category;
--whats is the total revenue generated for each category?
select
p.category,
sum(f.sales_amount) as revenue_by_category
from gold.fact_sales f
left join gold.dim_products p
on f.product_key=p.product_key
group by p.category
order by sum(f.sales_amount) DESC;
--Find total revenue is generated by each customer
select
c.customer_key,
c.first_name,
c.last_name,
count(f.sales_amount) as total_revenues
from gold.fact_sales f
left join gold.dim_customers c
on f.customer_key=c.customer_key
group by c.customer_key,c.first_name,c.last_name
order by count(f.sales_amount) ASC;
--Whats is the distribution of sold items across countries?
select
sum(f.quantity) as total_items_sold,
c.country
from gold.fact_sales f
left join gold.dim_customers c
on f.customer_key=c.customer_key
group by c.country
order by sum(f.quantity) DESC;